### ISSUE TITLE
question: default editor for rofi-finder

### ISSUE THREAD

**Issue by verajosemanuel** [carnager/rofi-scripts#21]
I have set vim as default editor in my settings and in .profile
but rofi-finder always opens Gedit
is there any way of setting vim as default editor?

**Comment by DaveDavenport** [comment]
I looked into the code, it uses [exo-open](https://linux.die.net/man/1/exo-open) to open the file. i don't know how `exo-open` resolves this.

**Comment by DaveDavenport** [comment]
XFCE documentation: https://docs.xfce.org/xfce/exo/preferred-applications
