### ISSUE TITLE
File finder: Can't open file pressing key Enter

### ISSUE THREAD

**Issue by Everest10** [carnager/rofi-scripts#29]
I run rofi -show find -modi find:~/.local/share/rofi/finder.sh and the rofi can find the file in your window search but when I press enter to open the file nothing happen. How to fix it ?

Distro: Fedora 36
WM: IceWM
Rofi: 1.7.3

I noticed this issue in the terminal ...

❯ rofi -show find -modi find:~/.local/share/rofi/finder.sh
xkbcommon: ERROR: /home/dom/.XCompose:4:14: unrecognized keysym "Ç" on left-hand side

.XCompose content ... (necessary to portuguese-br keyboard)
include "%L"

<dead_acute> <c> : "ç" ccedilla
<dead_acute> <Ç> : "Ç" ccedilla

but without the .XCompose file the same error happen, can't open the file pressing key enter.

**Comment by DaveDavenport** [comment]
for the xkbcommon error/warning ask xkbcommon.
Did you install exo-open?
https://github.com/davatorium/rofi-scripts/blob/master/rofi-finder/finder.sh#L12

**Comment by DaveDavenport** [comment]
closing, seems missing dependency.

**Comment by Everest10** [comment]
Tks Daven,

I did   $ dnf install exo  now it's works.
________________________________
De: Dave Davenport ***@***.***>
Enviado: quarta-feira, 20 de julho de 2022 05:30
Para: davatorium/rofi-scripts ***@***.***>
Cc: Wellington Melo ***@***.***>; Author ***@***.***>
Assunto: Re: [davatorium/rofi-scripts] File finder: Can't open file pressing key Enter (Issue #29)


for the xkbcommon error/warning ask xkbcommon.
Did you install exo-open?
https://github.com/davatorium/rofi-scripts/blob/master/rofi-finder/finder.sh#L12
